language: python

sudo: false

virtualenv:
  system_site_packages: false

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install -e ".[testing]"

script:
  - pytest

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master